---
apiVersion: skaffold/v2beta26
kind: Config
build:
  insecureRegistries:
    - registry.example.com
  local:
    push: true
  artifacts:
    - image: registry.example.com/kanopy-gateway-cert-controller
      ko:
        main: .
deploy:
  kubeContext: kind-kind
  kubectl:
    defaultNamespace: routing
    manifests:
      - examples/k8s/*.yaml
