---
apiVersion: skaffold/v2beta26
kind: Config
build:
  insecureRegistries:
    - registry.example.com
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: registry.example.com/kanopy-gateway-cert-controller
      kaniko:
        skipTLS: true
        buildArgs:
  cluster: {}
deploy:
  kubeContext: kind-kind
  kubectl:
    defaultNamespace: routing
    manifests:
      - examples/k8s/*.yaml
